apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastalert
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastalert
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: base-prod
                operator: In
                values:
                - base-prod
      containers:
      - image: registry.cn-beijing.aliyuncs.com/aoisola/elastalert:alpine-3.13
        imagePullPolicy: IfNotPresent
        name: elastalert
        command:
          - "/bin/start"
        resources:
          requests:
            cpu: 100m
            memory: 1024Mi
          limits:
            cpu: 2000m
            memory: 4096Mi
        volumeMounts:
        - name: elastalert-conf
          subPath: config.yaml
          mountPath: "/opt/conf/config.yaml"
        - name: elastalert-rules
          subPath: rule.yaml
          mountPath: "/opt/rules/rule.yaml"
        - name: elastalert-rules
          subPath: rule2.yaml
          mountPath: "/opt/rules/rule2.yaml"
        - name: elastalert-rules
          subPath: rule3.yaml
          mountPath: "/opt/rules/rule3.yaml"
        - name: elastalert-rules
          subPath: rule4.yaml
          mountPath: "/opt/rules/rule4.yaml"
        - name: elastalert-rules
          subPath: rule-edu-lms-checkin-server.yaml
          mountPath: "/opt/rules/rule-edu-lms-checkin-server.yaml"
        - name: elastalert-rules
          subPath: rule-edu-las-limitless-server.yaml
          mountPath: "/opt/rules/rule-edu-las-limitless-server.yaml"
        - name: elastalert-rules
          subPath: rule-edu-interaction-system.yaml
          mountPath: "/opt/rules/rule-edu-interaction-system.yaml"
        - name: elastalert-rules
          subPath: rule-edu-nps-project.yaml
          mountPath: "/opt/rules/rule-edu-nps-project.yaml"
      volumes:
      - name: elastalert-conf
        configMap:
          name: elastalert-conf
      - name: elastalert-rules
        configMap:
          name: elastalert-rules